# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84a81226f48de58e2351c4415195aa47a87f207d217bc636766b6aa833c4020e14faa5b9d96d75406935c28c68aacfc16424a6637c52a389aa7c627fbe9738d7

test:
  secret_key_base: b75664eb0fc44250cbb0a1bbf3afd8f5f0f3b7b6a97dfb16e551bfe59dc46562c2d93a43cde1fbcebe5cbfe6dde90b7b98ddc51e752a23afd4640d2f092da3e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
